### ISSUE TITLE
Not supported for piwik v3

### ISSUE THREAD

**Issue by ScaledByDesign** [halfer/piwik-database-configuration#1]
I installed it and got this message on the v3 build

Warning
The following plugins are not compatible with Piwik 3.0.0 and could not be loaded: DatabaseConfiguration.
You can update or uninstall these plugins on the Manage Plugins page.

**Comment by ScaledByDesign** [comment]
I fixed this by creating the plugin via the console

Turn on Development mode
./console development:enable

Generate the Plugin
./console generate:plugin --name=DatabaseConfiguration

Then I added the original code into the DatabaseConfiguration.php file

Then I activated the plugin 
./console plugin:activate DatabaseConfiguration

**Comment by halfer** [comment]
Thanks for the report. I've not upgraded to version 3.0, will do so presently.

I wonder if the new version should contain a class `DatabaseConfiguration3.php`, so that version 2.x is still supported?

**Comment by TFleury** [comment]
v3 just needs a `plugin.json` file.

**Comment by halfer** [comment]
Alright, this is done @UXPublishing and @TFleury - sorry for the delay. Only just got around to doing my upgrade!

It looks like this would be backwards compatible with 2.x so there's no need for a separate class.
